select * from employees;

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '__z__';

SELECT FIRST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE '%z%';

SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '_____';

SELECT * FROM JOBS WHERE JOB_TITLE LIKE '%Manager';